### ISSUE TITLE
Spotlight Component doesn't work as shown in the documentation example

### ISSUE THREAD

**Issue by Dudy83** [omnedia/ngx-spotlight#1]
Hello I wasn't able to make the [Spotlight Component](https://ngxui.com/docs/spotlight) as explained in the code example:
`
    <om-gridpattern [smallGrid]="true">
        <om-spotlight [animation]="true" styleClass="custom-spotlight">
            <div class="content">
                <h1>
                    Spotlight
                </h1>
            </div>
        </om-spotlight>
    </om-gridpattern>
`

the component GridPattern should be wrapped by the Spotlight component, otherwise it doesn't work.

Also, are you planning to add support for dark mode ? I'm not sure you are using the same stack as Aceternity.ui (TailwindCSS and ShadCN).

FYI: there is this library developped by angular community [Spartan NG](https://www.spartan.ng/) to had shadcn support for Angular.

thank you 👍

**Comment by xSentry** [comment]
Sorry, didnt see your Issue till now.
I have to look into it later.
But the code example does indeed work.
It is basically just a copy & paste of the code you see on the page.
So maybe its a styling issue?

Darkmode would need your own implementation right now.
You can style the components via global stylings. So you can add your own styling to the component from a global css / scss file.
